export default {
    zh: {
        wmsitninventoryrecorddif: {
            LabelWidth: "75px",
            LabelWidthForm: "100px",
            batchNo: "批次",
            dataCode: "DC",
            delayFrozenFlag: "有效期冻结",
            delayFrozenReason: "有效期冻结原因",
            delayReason: "延长有效期原因",
            delayTimes:"延期次数",
            delayToEndDate:"延长有效期至日期",
            difQty: "差异数量",
            driedScrapFlag: "是否烘干报废",
            driedTimes: "已烘干次数",
            expDate: "失效日期",
            exposeFrozenFlag: "暴露冻结",
            exposeFrozenReason: "暴露冻结原因",
            inspectionResult: "质检标记",
            inventoryDtlId: "盘点明细ID",
            inventoryNo: "盘点单号",
            inventoryQty: "盘点数量",
            inventoryRecordId: "盘点记录ID",
            leftMslTimes: "剩余湿敏时长",
            materialName: "物料名称",
            materialCode: "物料编码",
            materialSpec: "物料规格",
            mslGradeCode:"Msl等级编码",
            packageTime: "封包时间",
            palletBarcode: "载体条码",
            positionNo: "所在载体位置",
            productDate: "生产日期",
            projectNo: "项目号",
            proprietorCode: "货主",
            realExposeTimes: "实际暴露时长",
            skuCode:"SKU",
            stockCode:"库存编码",
            stockDtlId:"库存明细ID",
            supplierCode:"供应商编码",
            supplierExposeTimes:"供应商暴露时长",
            supplierName:"供应商名称",
            supplierNameAlias:"供应商名称Alias",
            supplierNameEn:"供应商名称En",
            uniicode:"唯一码",
            unpackTime:"开封时间",
            whouseNo:"仓库号",
            areaNo:"楼号",
            delFlag:"删除标记",
            erpWhouseNo:"ERP仓库",
            inwhTime:"入库时间",
            occupyQty:"占用数量",
            qty:"数量",
            unitCode:"单位",
            fileedId:"附件ID",
            fileedName:"附件名称",
            oldStockDtlId:"原库存明细ID",
            projectNoBak:"备用项目号",
            unpackStatus:"拆封状态",

        }
    },
    en: {
        wmsitninventoryrecorddif: {
            LabelWidth: "100px",
            LabelWidthForm: "120px",
            batchNo: "Batch Number",
            dataCode: "DC",
            delayFrozenFlag: "Delay Frozen Flag",
            delayFrozenReason: "Delay Frozen Reason",
            delayReason: "Delay Reason",
            delayTimes:"Delay Times",
            delayToEndDate:"Delay To End Date",
            difQty: "Different Qty",
            driedScrapFlag: "Dried Scrap Flag",
            driedTimes: "Dried Times",
            expDate: "Expiration Date",
            exposeFrozenFlag: "Expose Frozen Flag",
            exposeFrozenReason: "Expose Frozen Reason",
            inspectionResult: "Inspection Result",
            inventoryDtlId: "Inventory Detail ID",
            inventoryNo: "Inventory Number",
            inventoryQty: "Inventory Qty",
            inventoryRecordId: "Inventory Record ID",
            leftMslTimes: "Left Msl Times",
            materialName: "Material Name",
            materialCode: "Material Code",
            materialSpec: "Material Specification",
            mslGradeCode:"Msl Grade Code",
            packageTime: "Package Time",
            palletBarcode: "Pallet Barcode",
            positionNo: "Position Number",
            productDate: "Product Date",
            projectNo: "Project Number",
            proprietorCode: "Proprietor",
            realExposeTimes: "Real Expose Times",
            skuCode:"SKU",
            stockCode:"Stock Code",
            stockDtlId:"Stock Detail ID",
            supplierCode:"Supplier Code",
            supplierExposeTimes:"Supplier Expose Times",
            supplierName:"Supplier Name",
            supplierNameAlias:"Supplier Name Alias",
            supplierNameEn:"Supplier Name En",
            uniicode:"Uniicode",
            unpackTime:"Unpack Time",
            whouseNo:"Warehouse",
            areaNo:"Area Number",
            delFlag:"Delete Flag",
            erpWhouseNo:"ERP Warehouse",
            inwhTime:"Warehousing Time",
            occupyQty:"Occupy Qty",
            qty:"Qty",
            unitCode:"Unit Code",
            fileedId:"File ID",
            fileedName:"File Name",
            oldStockDtlId:"Old Stock Detail ID",
            projectNoBak:"Project Number Bak",
            unpackStatus:"UnpackStatus",
    }
  }
}
