export default {
    zh: {
        wmstaskhis: {
            LabelWidth: "75px",
            LabelWidthForm: "100px",
            feedbackDesc: "反馈信息",
            feedbackStatus: "反馈状态",
            frLocationNo: "起始位置",
            frLocationType: "起始位置类型",
            loadedType: "地址",
            matHeight: "物料高度",
            matLength: "物料长度",
            matQty: "数量",
            matWeight: "重量",
            matWidth: "物料宽度",
            orderNo: "单据号",
            palletBarcode: "托盘号",
            proprietorCode:"货主",
            regionNo: "库区",
            roadwayNo: "巷道",
            stockCode: "库存编码",
            taskDesc: "任务信息",
            taskPriority: "优先级",
            taskStatus:"任务状态",
            taskTypeNo: "任务类别",
            toLocationNo: "目的位置",
            toLocationType: "目的位置类型",
            whouseNo: "仓库",
            wmsTaskNo: "任务号",
            wmsTaskType: "任务类型"
        }
    },
    en: {
        wmstaskhis: {
            LabelWidth: "100px",
            LabelWidthForm: "120px",
            feedbackDesc: "Feedback",
            feedbackStatus: "FeedbackStatus",
            frLocationNo: "FromLocation",
            frLocationType: "FromLocationType",
            loadedType: "LoadedType",
            matHeight: "Height",
            matLength: "Length",
            matQty: "Qty",
            matWeight: "Weight",
            matWidth: "Width",
            orderNo: "DocNo",
            palletBarcode: "PalletBarcode",
            proprietorCode:"Proprietor",
            regionNo: "Region",
            roadwayNo: "Roadway",
            stockCode: "StockCode",
            taskDesc: "TaskInformation",
            taskPriority: "Priority",
            taskStatus:"Status",
            taskTypeNo: "TaskType",
            toLocationNo: "TargetLocation",
            toLocationType: "TargetLocationType",
            whouseNo: "Whouse",
            wmsTaskNo: "TaskNo",
            wmsTaskType: "WMSTaskType"
    }
  }
}
