export default {
    zh: {
        wmsstockdtlhis: {
            LabelWidth: "75px",
            LabelWidthForm: "100px",
            areaNo: "楼号",
            erpWhouseNo: "ERP 仓库",
            inspectionResult: "质检结果",
            lockFlag: "锁定",
            lockReason: "锁定原因",
            materialName:"物料名称",
            materialCode:"物料编码",
            materialSpec: "物料规格",
            occupyQty: "占用数量",
            palletBarcode: "托盘码",
            projectNo: "项目号",
            proprietorCode: "货主",
            qty: "数量",
            skuCode: "SKU",
            stockCode: "库存编码",
            stockDtlStatus:"库存明细状态",
            supplierCode: "供应商编码",
            supplierName: "供应商名称",
            supplierNameAlias: "供应商名称Alias",
            supplierNameEn: "供应商名称EN",
            whouseNo: "仓库",
            unitCode: "单位",
        }
    },
    en: {
        wmsstockdtlhis: {
            LabelWidth: "100px",
            LabelWidthForm: "120px",
            areaNo: "Area No",
            erpWhouseNo: "ERP Warehouse",
            inspectionResult: "Inspection Result",
            lockFlag: "Lock",
            lockReason: "Lock Reason",
            materialName:"Material Name",
            materialCode:"Material Code",
            materialSpec: "Material Specification",
            occupyQty: "Occupy Qty",
            palletBarcode: "Pallet Barcode",
            projectNo: "Project No",
            proprietorCode: "Proprietor Code",
            qty: "Qty",
            skuCode: "SKU",
            stockCode: "Stock Code",
            stockDtlStatus:"StockDtl Status",
            supplierCode: "Supplier Code",
            supplierName: "Supplier Name",
            supplierNameAlias: "Supplier Name Alias",
            supplierNameEn: "Supplier Name EN",
            whouseNo: "WareHouse",
            unitCode: "Unit Code",
    }
  }
}
