export default {
    zh: {
        wmsstockuniicode: {
            LabelWidth: "75px",
            LabelWidthForm: "100px",
            areaNo: "来源",
            batchNo: "批次",
            dataCode: "DC",
            delayFrozenFlag: "有效期冻结",
            delayFrozenReason: "有效期冻结原因",
            delayReason: "延长有效期原因",
            delayTimes: "延期次数",
            delayToEndDate: "DAF 贴膜时间",
            driedScrapFlag: "是否烘干报废",
            driedTimes: "已烘干次数",
            erpWhouseNo: "ERP仓库",
            expDate: "DAF 过期时间",
            exposeFrozenFlag:"暴露冻结标志",
            exposeFrozenReason:"暴露冻结原因",
            inspectionResult:"质检结果",
            inwhTime:"入库时间",
            leftMslTimes:"剩余湿敏时长",
            materialName:"物料名称",
            materialCode:"物料编码",
            materialSpec: "物料规格",
            mslGradeCode: "MSL等级",
            occupyQty: "占用数量",
            packageTime: "封包时间",
            palletBarcode: "载体条码",
            positionNo: "位置",
            productDate: "生产日期",
            projectNo: "工单号",
            proprietorCode: "货主",
            realExposeTimes: "实际暴露时长",
            skuCode: "SKU",
            stockCode: "库存编码",
            stockDtlId: "库存明细ID",
            qty: "库存数量",
            supplierCode: "客户代码",
            supplierExposeTimes: "供应商暴露时长",
            supplierName: "供应商名称",
            supplierNameAlias: "供应商名称Alias",
            supplierNameEn: "供应商名称EN",
            uniicode: "唯一码",
            unpackStatus: "是否下单",
            unpackTime: "开封时间",
            unitCode: "单位",
            whouseNo: "仓库",
            chipSize:"芯片尺寸",
            chipThickness:"芯片厚度",
            chipModel:"芯片型号",
            dafType:"DAF型号",
            stockStatus:"库存状态",
            binNo:"货位"
        }
    },
    en: {
        wmsstockuniicode: {
            LabelWidth: "100px",
            LabelWidthForm: "120px",
            areaNo: "Source By",
            batchNo: "Batch No",
            dataCode: "DC",
            delayFrozenFlag: "Delay Frozen Flag",
            delayFrozenReason: "Delay Frozen Reason",
            delayReason: "Delay Reason",
            delayTimes: "Delay Times",
            delayToEndDate: "DAF Film App Time",
            driedScrapFlag: "Dried Scrap Flag",
            driedTimes: "Dried Times",
            erpWhouseNo: "ERP Warehouse",
            expDate: "DAF Expiry Date",
            exposeFrozenFlag:"Expose Frozen Flag",
            exposeFrozenReason:"Expose Frozen Reason",
            inspectionResult:"Inspection Result",
            inwhTime:"In Warehouse Time",
            leftMslTimes:"LeftMslTimes",
            materialName:"Material Name",
            materialCode:"Material Code",
            materialSpec: "Material Specification",
            mslGradeCode: "MSLGradeCode",
            occupyQty: "Occupy Qty",
            packageTime: "Package Time",
            palletBarcode: "Pallet Barcode",
            positionNo: "PositionNo",
            productDate: "Product Date",
            projectNo: "Invoice No",
            proprietorCode: "Proprietor Code",
            realExposeTimes: "Real Expose Times",
            skuCode: "SKU",
            stockCode: "Stock Code",
            stockDtlId: "Stock DetailId",
            qty: "Stock Qty",
            supplierCode: " Customer No",
            supplierExposeTimes: "Supplier Expose Times",
            supplierName: "Supplier Name",
            supplierNameAlias: "Supplier Name Alias",
            supplierNameEn: "Supplier Name EN",
            uniicode: "Uniicode",
            unpackStatus: "Is Order",
            unpackTime: "Unpack Time",
            unitCode: "Unit Code",
            whouseNo: "Warehouse",
            chipSize:"Chip Size",
            chipThickness:"Chip Thickness",
            chipModel:"Chip Model",
            dafType:"Daf Type",
            stockStatus:"Stock Status",
            binNo:"Bin No"
    }
  }
}
