export default {
    zh: {
        wmsoutinvoicedtl: {
            LabelWidth: "75px",
            LabelWidthForm: "100px",
            allocatResult: "分配结果",
            allotQty: "已分配数量",
            areaNo: "楼号",
            assemblyIdx: "装配顺序",
            batchNo: "批次",
            belongDepartment: "归属事业部",
            completeQty: "已完成数量",
            docTypeCode:"单据类型",
            erpUndeliverQty: "ERP未发数量",
            erpWhouseNo: "ERP仓库",
            externalOutDtlId: "外部出库单行号",
            externalOutNo: "外部出库单号",
            invoiceDtlStatus: "发货单明细状态",
            invoiceNo:"WMS发货单号",
            materialName: "物料名称",
            materialCode: "物料编码",
            materialSpec: "规格",
            orderDtlId: "单据明细ID",
            orderNo: "单据号",
            productLocation:"生产地点",
            productDeptCode: "生成部门编码",
            productDeptName: "生成部门名称",
            projectNo: "项目号",
            proprietorCode: "货主",
            invoiceQty: "单据数量",
            putdownQty: "已下架数量",
            productSn:"序列号",
            originalSn: "原序列号",
            supplyType: "供应类型",
            ticketPlanBeginTime: "工单计划开始时间",
            waveNo: "波次号",
            whouseNo: "仓库",
            companyCode: "公司代码",
            supplierCode:"供应商编号",
            supplierName: "供应商名称",
            supplierNameEn: "供应商名称EN",
            supplierNameAlias: "供应商名称Alias",
            ticketNo: "工单号",
            unitCode: "单位",
            inspectionResult:"质检结果",
            inspectionResultDesc:"质检结果",
            qty:"库存数量",
            occupyQty:"占用数量",
            unitName: "单位"
        }
    },
    en: {
        wmsoutinvoicedtl: {
            LabelWidth: "100px",
            LabelWidthForm: "120px",
            allocatResult: "Allocation result",
            allotQty: "Allocated quantity",
            areaNo: "Area",
            assemblyIdx: "Assembly sequence",
            batchNo: "Batch",
            belongDepartment: "Belong to the business division",
            completeQty: "Completed quantity",
            docTypeCode:"Document Type",
            erpUndeliverQty: "Unshipped quantity in ERP",
            erpWhouseNo: "ERP Warehouse",
            externalOutDtlId: "External outbound single line number",
            externalOutNo: "External outbound order number",
            invoiceDtlStatus: "Invoice Status",
            invoiceNo:"Invoice Number",
            materialName: "Material Name",
            materialCode: "Material Code",
            materialSpec: "Specification",
            orderDtlId: "Document detail ID",
            orderNo: "Document number",
            productLocation:"Production Location",
            productDeptCode: "Production Department",
            productDeptName: "Production Department Name",
            projectNo: "Project Number",
            proprietorCode: "Proprietor",
            invoiceQty: "Qty",
            putdownQty: "Put Down Qty",
            productSn:"SN",
            originalSn: "OriginalSn",
            supplyType: "Supply Type",
            ticketPlanBeginTime: "Ticket Plan",
            waveNo: "Wave Number",
            whouseNo: "Warehouse",
            companyCode: "Company",
            supplierCode:"Supplier Code",
            supplierName: "Supplier",
            supplierNameEn: "Supplier",
            supplierNameAlias: "Supplier",
            ticketNo: "Ticket Number",
            unitCode: "Unit Code",
            inspectionResult:"Inspection Result",
            qty:"Stock Qty",
            occupyQty:"Occupy Qty",
            unitName: "Unit Name",
            inspectionResultDesc:"Inspection Result"
    }
  }
}
