export default {
    zh: {
        wmsinreceiptrecord: {
            LabelWidth: "75px",
            LabelWidthForm: "100px",
            areaNo: "楼号",
            binNo: "库位",
            batchNo: "批次",
            departmentName: "部门",
            docTypeCode: "单据类型",
            erpWhouseNo:"ERP仓库",
            externalInDtlId:"外部单行号",
            externalInNo: "外部单号",
            inNo: "入库单号",
            inDtlId: "入库明细单ID",
            inOutName: "出入名称",
            inOutTypeNo: "出入类型",
            inspectionResult: "质检结果",
            inspector: "质检员",
            iqcResultNo:"质检结果单号",
            inRecordStatus: "入库状态",
            loadedType: "装载类型",
            materialName: "物料名称",
            materialCode: "物料编码",
            materialSpec: "物料规格",
            palletBarcode: "托盘号",
            orderDtlId: "单据行号",
            orderNo: "单据号",
            ptaRegionNo:"上架库区",
            ptaStockCode:"上架库存编码",
            ptaStockDtlId: "上架库存明细ID",
            proprietorCode: "货主",
            minPkgQty: "最小包装量",
            projectNo: "项目号",
            ptaBinNo: "上架库位",
            ptaPalletBarcode: "上架托盘",
            receiptNo: "收货单号",
            recordQty: "收货数量",
            receiptDtlId: "收货明细ID",
            regionNo: "库区",
            returnResult: "返回结果",
            replenishFlag: "补货标记",
            returnFlag: "回传标记",
            returnTime: "回传时间",
            skuCode:"SKU编码",
            sourceBy:"来源",
            stockCode: "库存编码",
            stockDtlId: "库存明细ID",
            supplierCode: "供应商编码",
            supplierName: "供应商",
            supplierNameAlias: "供应商Alias",
            supplierNameEn: "供应商EN",
            ticketNo: "工单号",
            urgentFlag: "急料标记",
            unitCode: "单位",
            whouseNo:"仓库"
        }
    },
    en: {
        wmsinreceiptrecord: {
            LabelWidth: "100px",
            LabelWidthForm: "120px",
            areaNo: "Area No",
            binNo: "Bin No",
            batchNo: "Batch No",
            departmentName: "Department Name",
            docTypeCode: "DocTypeCode",
            erpWhouseNo:"ERP Whouse",
            externalInDtlId:"ExternalInDtlId",
            externalInNo: "ExternalInNo",
            inNo: "InNo",
            inDtlId: "InDtlId",
            inOutName: "InOutName",
            inOutTypeNo: "InOutType",
            inspectionResult: "InspectionResult",
            inspector: "Inspector",
            iqcResultNo:"IqcResultNo",
            inRecordStatus: "InRecordStatus",
            loadedType: "Loaded Type",
            materialName: "Material Name",
            materialCode: "Material Code",
            materialSpec: "Material Specification",
            palletBarcode: "Pallet Barcode",
            orderDtlId: "Order DtlId",
            orderNo: "Order No",
            ptaRegionNo:"Pta RegionNo",
            ptaStockCode:"Pta StockCode",
            ptaStockDtlId: "Pta StockDtlId",
            proprietorCode: "Proprietor Code",
            minPkgQty: "Min Packet Qty",
            projectNo: "Project No",
            ptaBinNo: "PtaBinNo",
            ptaPalletBarcode: "PtaPalletBarcode",
            receiptNo: "ReceiptNo",
            recordQty: "ReceiptQty",
            receiptDtlId: "ReceiptDtlId",
            regionNo: "RegionNo",
            returnResult: "Return Result",
            replenishFlag: "Replenish Flag",
            returnFlag: "Return Flag",
            returnTime: "Return Time",
            skuCode:"SKU Code",
            sourceBy:"Source By",
            stockCode: "Stock Code",
            stockDtlId: "StockDtlId",
            supplierCode: "SupplierCode",
            supplierName: "SupplierName",
            supplierNameAlias: "SupplierNameAlias",
            supplierNameEn: "SupplierNameEN",
            ticketNo: "TicketNo",
            urgentFlag: "UrgentFlag",
            unitCode: "Unit Code",
            whouseNo:"Warehouse"
    }
  }
}
