export default {
    zh: {
        wmsoutinvoicerecordhis: {
            LabelWidth: "75px",
            LabelWidthForm: "100px",
            allocatResult: "分配结果",
            allotQty: "分配数量",
            allotType: "分配类型",
            docTypeCode: "单据类型",
            areaNo: "来源",
            assemblyIdx: "装配顺序",
            batchNo: "批次",
            belongDepartment: "归属事业部",
            binNo: "库位",
            deliveryLocNo: "发货站台",
            erpWhouseNo: "ERP仓库",
            externalOutDtlId: "外部单行号",
            externalOutNo:"外部单号",
            fpName: "成品名称",
            fpNo: "成品编码",
            fpQty: "成品数量",
            inOutName: "出入名称",
            inOutTypeNo: "出入名称",
            inspectionResult:"质检结果",
            invoiceDtlId: "发货单明细ID",
            invoiceNo: "发货单号",
            isBatch: "批次管理",
            issuedResult: "发布结果",
            materialName: "物料名称",
            materialCode: "物料编码",
            materialSpec: "物料规格",
            orderDtlId: "单据明细ID",
            orderNo: "单据号",
            outRecordStatus: "出库状态",
            palletBarcode: "托盘号",
            palletPickType: "托盘拣选类型",
            pickLocNo: "拣选站台",
            pickQty: "拣选数量",
            pickTaskNo: "出库单号",
            pickType: "拣选类型",
            preStockDtlId: "下架库存明细ID",
            productDeptCode: "产品部门",
            productDeptName: "产品部门",
            productLocation: "产品部门",
            projectNo: "工单号",
            proprietorCode: "货主",
            regionNo: "库区",
            reversePickFlag: "反拣标志",
            skuCode: "SKU",
            sourceBy: "来源",
            stockCode: "库存编码",
            stockDtlId: "库存明细ID",
            supplierCode: "供应商编码",
            supplierName: "供应商名称",
            supplierNameAlias: "供应商名称Alias",
            supplierNameEn: "供应商名称EN",
            supplyType: "供应商类型",
            ticketNo: "工单号",
            ticketPlanBeginTime: "工单开始时间",
            ticketType: "工单类型",
            unitCode: "单位",
            waveNo: "波次号",
            whouseNo: "仓库",
            operationMode: "操作模式",
            outBarCode: "出库条码",
            urgentFlag: "急料标志",
            loadedTtype: "装载类型",
            productSn: "产品序列号"
        }
    },
    en: {
        wmsoutinvoicerecordhis: {
            LabelWidth: "100px",
            LabelWidthForm: "120px",
            allocatResult: "Allocat Result",
            allotQty: "Allot Qty",
            allotType: "Allot Type",
            docTypeCode: "DocTypeCode",
            areaNo: "Source By",
            assemblyIdx: "AssemblyIdx",
            batchNo: "BatchNo",
            belongDepartment: "BelongDepartment",
            binNo: "BinNo",
            deliveryLocNo: "DeliveryLocNo",
            erpWhouseNo: "ErpWhouseNo",
            externalOutDtlId: "ExternalOutDtlId",
            externalOutNo:"ExternalOutNo",
            fpName: "FpName",
            fpNo: "FpNo",
            fpQty: "FpQty",
            inOutName: "InOutName",
            inOutTypeNo: "InOutTypeNo",
            inspectionResult:"InspectionResult",
            invoiceDtlId: "InvoiceDtlId",
            invoiceNo: "InvoiceNo",
            isBatch: "IsBatch",
            issuedResult: "IsSuedResult",
            materialName: "MaterialName",
            materialCode: "MaterialCode",
            materialSpec: "MaterialSpecification",
            orderDtlId: "OrderDtlId",
            orderNo: "OrderNo",
            outRecordStatus: "OutRecordStatus",
            palletBarcode: "PalletBarcode",
            palletPickType: "PalletPickType",
            pickLocNo: "PickLocNo",
            pickQty: "PickQty",
            pickTaskNo: "PickTaskNo",
            pickType: "PickType",
            preStockDtlId: "PreStockDtlId",
            productDeptCode: "ProductDeptCode",
            productDeptName: "ProductDeptName",
            productLocation: "ProductLocation",
            projectNo: "ProjectNo",
            proprietorCode: "ProprietorCode",
            regionNo: "RegionNo",
            reversePickFlag: "ReversePickFlag",
            skuCode: "SKU",
            sourceBy: "SourceBy",
            stockCode: "StockCode",
            stockDtlId: "StockDtlId",
            supplierCode: "SupplierCode",
            supplierName: "SupplierName",
            supplierNameAlias: "SupplierName",
            supplierNameEn: "SupplierName",
            supplyType: "SupplyType",
            ticketNo: "TicketNo",
            ticketPlanBeginTime: "TicketPlanBeginTime",
            ticketType: "TicketType",
            unitCode: "UnitCode",
            waveNo: "WaveNo",
            whouseNo: "Warehouse",
            operationMode: "OperationMode",
            outBarCode: "OutBarcode",
            urgentFlag: "UrgentFlag",
            loadedTtype: "LoadedType",
            productSn: "ProductSn"

    }
  }
}
