export default {
    zh: {
        wmsitninventoryrecordhis: {
            LabelWidth: "75px",
            LabelWidthForm: "100px",
            blindFlag: "盘点方法",
            confirmBy: "盘点确认人",
            confirmQty: "盘点确认数量",
            confirmReason: "盘点差异原因",
            differenceFlag: "差异标识",
            docTypeCode:"单据类型",
            erpWhouseNo:"ERP仓库",
            inspectionResult: "质检标记",
            inventoryBy: "盘点操作人",
            inventoryDtlId: "盘点明细ID",
            inventoryNo: "盘点单号",
            inventoryQty: "盘点数量",
            inventoryReason: "盘点操作原因",
            inventoryRecordStatus: "盘点状态",
            materialName: "物料名称",
            materialCode: "物料编码",
            materialSpec: "物料规格",
            occupyQty: "占用数量",
            palletBarcode: "载体条码",
            proprietorCode: "货主",
            projectNo: "项目号",
            putdownLocNo: "下架站台",
            skuCode:"SKU编码",
            stockCode: "库存编码",
            stockDtlId: "库存明细ID",
            stockQty: "库存数量",
            supplierCode: "供应商编码",
            supplierName: "供应商",
            supplierNameAlias: "供应商Alias",
            supplierNameEn: "供应商EN",
            whouseNo:"仓库",
            inOutTypeNo:"出入库类别"
        }
    },
    en: {
        wmsitninventoryrecordhis: {
            LabelWidth: "100px",
            LabelWidthForm: "120px",
            blindFlag: "Inventory Fancation",
            confirmBy: "Comfirm By",
            confirmQty: "Comfirm Qty",
            confirmReason: "Comfirm Reason",
            differenceFlag: "Difference Flag",
            docTypeCode:"Document Type Code",
            erpWhouseNo:"ERP Warehouse",
            inspectionResult: "Inspection Result",
            inventoryBy: "Inventory By",
            inventoryDtlId: "Inventory Detail ID",
            inventoryNo: "Inventory Number",
            inventoryQty: "Inventory Qty",
            inventoryReason: "Inventory Reason",
            inventoryRecordStatus: "Inventory Status",
            materialName: "Material Name",
            materialCode: "Material Code",
            materialSpec: "Material Specification",
            occupyQty: "Occupy Qty",
            palletBarcode: "Pallet Barcode",
            proprietorCode: "Propriator",
            projectNo: "Project Number",
            putdownLocNo: "Put Down Loc",
            skuCode:"SKU",
            stockCode: "Stock Code",
            stockDtlId: "Stock Detail ID",
            stockQty: "Stock Qty",
            supplierCode: "Supplier Code",
            supplierName: "Supplier Name",
            supplierNameAlias: "Supplier Name Alias",
            supplierNameEn: "Supplier Name EN",
            whouseNo:"Warehouse",
            inOutTypeNo:"In Or Out"
    }
  }
}
