export default {
    zh: {
        srmcmdhis: {
            LabelWidth: "75px",
            LabelWidthForm: "100px",
            SubTask_No: "指令号",
            Task_No: "任务号",
            Serial_No: "流水号",
            Device_No: "设备号",
            Fork_No: "货叉",
            Station_Type: "站台类型",
            Check_Point: "校验位",
            Task_Cmd: "指令类型",
            Task_Type: "任务类型",
            Pallet_Barcode: "托盘号",
            WaferID:"晶圆ID",
            Exec_Status: "指令状态",
            Remark_Desc:"备注",
            From_Station: "起始站台",
            From_ForkDirection:"起始排",
            From_Column: "起始列",
            From_Layer: "起始层",
            From_Deep: "起始深度",
            To_Station: "目的站台",
            To_ForkDirection: "目的排",
            To_Column:"目的列",
            To_Layer: "目的层",
            To_Deep: "目的深",
            Recive_Date: "接收时间",
            Begin_Date: "开始时间",
            Pick_Date: "取货时间",
            Put_Date: "放货时间",
            Finish_Date: "结束时间"
        }
    },
    en: {
        srmcmdhis: {
            LabelWidth: "100px",
            LabelWidthForm: "120px",
            SubTask_No: "Command No",
            Task_No: "WMS Task No",
            Serial_No: "Serial No",
            Device_No: "Device No",
            Fork_No: "Fork No",
            Station_Type: "Station Type",
            Check_Point: "Check Point",
            Task_Cmd: "Command Type",
            Task_Type: "Task Type",
            Pallet_Barcode: "Pallet Barcode",
            WaferID:"WaferID",
            Exec_Status: "Command Status",
            Remark_Desc:"Remark",
            From_Station: "From Station",
            From_ForkDirection:"From Row",
            From_Column: "From Column",
            From_Layer: "From Layer",
            From_Deep: "From Deep",
            To_Station: "To Station",
            To_ForkDirection: "To Row",
            To_Column:"To Column",
            To_Layer: "To Layer",
            To_Deep: "To Deep",
            Recive_Date: "Receive Date",
            Begin_Date: "Begin Date",
            Pick_Date: "Pick Up Date",
            Put_Date: "Put Down Date",
            Finish_Date: "Finish Date"
    }
  }
}
